### ISSUE TITLE
关于状态改变的疑问

### ISSUE THREAD

**Issue by zelong8861** [shoukai/tools-journey#1]
https://github.com/shoukai/tools-journey/blob/3336ef77b63ba64ec09e573316ba1a35f0b0e1c4/spring-statemachine-sample/src/main/java/org/apframework/statemachine/StatemachineConfigurer.java#L49

您好 我的理解这里 TurnstileStates.Unlocked 到 TurnstileStates.Locked 所依赖的事件应该是PUSH 对应的action 为customerPassAndLock() 
小弟初学 请多多指教~

**Comment by shoukai** [comment]
> [tools-journey/spring-statemachine-sample/src/main/java/org/apframework/statemachine/StatemachineConfigurer.java](https://github.com/shoukai/tools-journey/blob/3336ef77b63ba64ec09e573316ba1a35f0b0e1c4/spring-statemachine-sample/src/main/java/org/apframework/statemachine/StatemachineConfigurer.java#L49)
> 
> Line 49 in [3336ef7](/shoukai/tools-journey/commit/3336ef77b63ba64ec09e573316ba1a35f0b0e1c4)
> 
>  .event(TurnstileEvents.COIN).action(customerPassAndLock()) 
> 您好 我的理解这里 TurnstileStates.Unlocked 到 TurnstileStates.Locked 所依赖的事件应该是PUSH 对应的action 为customerPassAndLock()
> 小弟初学 请多多指教~

嗯，逻辑上写反了，我修正一下
